In [1]:
import pandas as pd

In [17]:
df = pd.DataFrame({
        "Order date":[
            "2024-01-10",
            "2024-01-15",
            "2024-02-05",
            "2024-02-12",
            "2024-03-01",
            "2024-03-15",
            "2024-04-20",
            "2024-05-05",
            "2024-06-06",
            "2024-06-11"
        ],

        "Product Name":[
            "Laptop",
             "mouse",
            "printer",
            "Tablet",
            "Laptop",
            "Moniter",
            "Mouse",
            "Smartwatch",
            "Mouse",
            "Printer"
        ],
        "Categary":[
            "Electrics",
            "Accesaries",
            "Ofice",
            "Electrics",
            "Ofice",
            "Electrics",
            "Accesaries",
            "Electrics",
            "Accesaries",
            "Electrics"
        ],
        "region":[
            "North",
            "South",
            "East",
            "Weast",
            "North",
            "South",
            "East",
            "Weast",
            "North",
            "South"
        ],
            "Quantity":[
                2,
                5,
                3,
                4,
                1,
                2,
                6,
                2,
                3,
                5
            ],
            "sales":[
                50000,
                2500,
                9000,
                30000,
                55000,
                16000,
                3000,
                6000,
                45000,
                2500
            ],
            "Profit":[
                10000,
                5000,
                2000,
                2000,
                3000,
                20000,
                30000,
                20000,
                10000,
                20000
    ],
})

In [20]:
print("Original Database")
print("-",50)
display(df)

Original Database
- 50

   Order date Product Name    Categary region  Quantity  sales  Profit
0  2024-01-10       Laptop   Electrics  North         2  50000   10000
1  2024-01-15        mouse  Accesaries  South         5   2500    5000
2  2024-02-05      printer       Ofice   East         3   9000    2000
3  2024-02-12       Tablet   Electrics  Weast         4  30000    2000
4  2024-03-01       Laptop       Ofice  North         1  55000    3000
5  2024-03-15      Moniter   Electrics  South         2  16000   20000
6  2024-04-20        Mouse  Accesaries   East         6   3000   30000
7  2024-05-05   Smartwatch   Electrics  Weast         2   6000   20000
8  2024-06-06        Mouse  Accesaries  North         3  45000   10000
9  2024-06-11      Printer   Electrics  South         5   2500   20000

In [23]:
print("Duplicate Record")
print("-"*50)
print(df.duplicated().sum())

Duplicate Record
--------------------------------------------------
0

In [24]:
print("Duplicated Record")
print("-"*50)
print(df[df.duplicated()])

Duplicated Record
--------------------------------------------------
Empty DataFrame
Columns: [Order date, Product Name, Categary, region, Quantity, sales, Profit]
Index: []

In [30]:
print("Concatenation")
print("-"*50)
new_sales=pd.DataFrame ({
    "Order Date":
    [
        "2024-06-09",
        "2024-07-28",
        "2024-07-30"
    ],
    "Product name":
    [
        "Laptop",
        "Mouse",
        "Printer"
    ],
    "Categary":
    [
        "Electrics",
        "Ofice",
        "Electrics"
    ],
    "region":
    [
        "North",
        "South",
        "East"
    ],
    "Quantity":
    [
        2,
        4,
        8
    ],
    "Sales":
    [
        39000,
        20993,
        93000
    ],
    "Profit":
    [
        200000,
        300000,
        657758
    ],
})

Concatenation
--------------------------------------------------

In [28]:
print("New sales")
display(new_sales)

New sales

   Order Date Product name   Categary region  Quantity  Sales  Profit
0  2024-06-09       Laptop  Electrics  North         2  39000  200000
1  2024-07-28        Mouse      Ofice  South         4  20993  300000
2  2024-07-30      Printer  Electrics   East         8  93000  657758

In [39]:
region_info=pd.DataFrame({
    "Region_manager":
    [
        "Manager A",
        "Manager B",
        "Manager C",
        "Manager D"
    ],
    "region":
    [
        "North",
        "South",
        "Weast",
        "East"
    ]
        })

In [42]:
df_region=df.set_index("region")
joined_df=df_region.join(region_info)
print(joined_df)

        Order date Product Name    Categary  Quantity  sales  Profit  \
region
North   2024-01-10       Laptop   Electrics         2  50000   10000
South   2024-01-15        mouse  Accesaries         5   2500    5000
East    2024-02-05      printer       Ofice         3   9000    2000
Weast   2024-02-12       Tablet   Electrics         4  30000    2000
North   2024-03-01       Laptop       Ofice         1  55000    3000
South   2024-03-15      Moniter   Electrics         2  16000   20000
East    2024-04-20        Mouse  Accesaries         6   3000   30000
Weast   2024-05-05   Smartwatch   Electrics         2   6000   20000
North   2024-06-06        Mouse  Accesaries         3  45000   10000
South   2024-06-11      Printer   Electrics         5   2500   20000

       Region_manager Region
region
North             NaN    NaN
South             NaN    NaN
East              NaN    NaN
Weast             NaN    NaN
North             NaN    NaN
South             NaN    NaN
East              NaN    NaN
Weast             NaN    NaN
North             NaN    NaN
South             NaN    NaN

In [43]:
region_sales=df.groupby(
    "region"
)["sales"].sum()
print("Total sales by region")
display(region_sales)

Total sales by region

region
East      12000
North    150000
South     21000
Weast     36000
Name: sales, dtype: int64

In [47]:
pivot_table=pd.pivot_table(
    df,
    values="sales",
    index="Categary",
    columns="region",
    aggfunc="sum",
    fill_value=0
)

In [48]:
print(pivot_table)

region      East  North  South  Weast
Categary
Accesaries  3000  45000   2500      0
Electrics      0  50000  18500  36000
Ofice       9000  55000      0      0